@startuml

stereotype "Library"{
    Jsoup
    Gson
    TelegramBots
    Lombok
}

"Library" <.. "Application" : use

package "Application"{

    interface CurrencyService{
        + getRate(Currency c) : double
    }

    class PrivatBankCurrencyService

    class TelegramBotService

    enum Currency{
        USD
        EUR
        UAH
    }

    PrivatBankCurrencyService --|> CurrencyService

}

@enduml